# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
      web.vm.box = "ubuntu/xenial64"
      web.vm.provider :virtualbox do |vb|
        vb.customize [ 'modifyvm', :id, '--name', 'web' ]
      end
  end
  config.vm.define "db" do |db|
      db.vm.box = "ubuntu/xenial64"
      db.vm.provider :virtualbox do |vb|
        vb.customize [ 'modifyvm', :id, '--name', 'db' ]
      end
  end
end

